version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:10.16.3
    steps:
      - checkout
      - run:
          name: update npm
          command: "npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm install
      - run: |
          apt-get yes | update
          apt install default-jdk    
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: run space test
          command: npm test
      - store_artifacts:
          path: ~/repo/space
      - sonarcloud/scan

workflows:
  main:
   jobs:
     - build:
         context: SonarCloud
